# Introduction

Normative reference ranges have been widely used as a cornerstone in clinical medicine to quickly screen a large number of subject-specific measurements, including anthropometry metrics, laboratory values, and vital signs, and identify abnormal measurements that may warrant further attention [@oconnorNormativeDataTheir1990; @jonesReferenceIntervals2008; @weirBMIClassificationPercentile2024]. In recent decades, there has been growing interest in modeling such reference ranges as they change across age and sex as normative lifespan charts, borrowing from the idea of pediatric growth charts to highlight that different normative reference ranges may be applicable to individuals of different ages [@bethlehemBrainChartsHuman2022; @coleAgeSizerelatedReference2009; @coleBodyMassIndex1995; @whomulticentregrowthreferencestudygroupWHOChildGrowth2006].

In order to estimate such normative charts, the World Health Organization has recommended the use of Generalized Additive Models for Location, Scale, and Shape (GAMLSS) as a robust and flexible framework for modeling non-linear growth trajectories [@borghiConstructionWorldHealth2006; @rigbySemiparametricAdditiveModel1996; @rigbyGeneralizedAdditiveModels2005; TODO JSTATSOFT]. The GAMLSS framework extends generalized linear models (GLM) and generalized additive models (GAM) such that outcome variables to follow a highly general family of distributions, including skewed and heavy-tailed distributions as well as zero-inflated distributions [@hastieGeneralizedAdditiveModels1986]. Within this framework, GAMLSS allows for semi-parametric modeling of not only the mean of the outcome variable, but also the variance, skewness, and kurtosis of the outcome for any given explanatory variables. This is essential in the context of normative charts, as it is reasonable to assume higher-order moments change with age, sex, setting, and other demographic variables due to high degrees of heterogeneity in the human population. Thus, instead of only providing predictions for the reference mean, GAMLSS provides predicted reference distributions and therefore normative charts. Importantly, despite the high degree of flexibility provided by the GAMLSS framework, GAMLSS-based normative charts retain significant transparency and interpretability due to their semi-parametric nature such that GAMLSS models can be checked for adequate model fit.

Notably, large sample sizes are required for stable fitting of GAMLSS models, especially as the complexity of the model grows via increases in the number of explanatory variables included, increased non-linearity of the smooth terms, and estimation of higher-order moments. In the context of normative charts, even larger sample sizes may be necessary in order to accurately estimate the relatively extreme quantiles that may be of interest (i.e. to identify abnormal measurements below the 2.5 percentile or above the 97.5 percentile). 

Optimally, estimation of normative charts has relied on purposeful collection of large multi-site datasets in combination with aggregation of pre-existing smaller research datasets through data use agreements. However, due to challenges with obtaining multi-site integrated datasets, normative charts often rely on datasets from single institutions that may be more homogeneous and less representative of the broader population . Ideally, if individual patient data (IPD) could be easily shared across multiple institutions, normative charts fit on such data could be confidently applied across a more general population. This is especially true if the IPD is obtained from a clinical database. However, since IPD is typically protected by governmental and institutional privacy regulations, sharing of IPD across institutions can often be infeasible.

In settings where IPD cannot be aggregated, privacy-preserving distributed algorithms can be used for federated learning. These algorithms seek to enable standard model fitting while only requiring iterative sharing of a small number of aggregate summary statistics from each site. While distributed algorithms have been proposed for generalized linear models and generalized additive models, an algorithm for fitting distributed GAMLSS (dGAMLSS) has not yet been proposed [@liReviewApplicationsFederated2020; @pfitznerFederatedLearningMedical2021; @yinComprehensiveSurveyPrivacypreserving2021].

To extend normative chart modeling to cover broader patient populations and provide more accurate reference quantile estimation, we propose a novel exact distributed algorithm to fit GAMLSS. dGAMLSS allows for distributed fitting of fully-parametric and semi-parametric models for all GAMLSS family distributions, including models using automated penalty selection. We demonstrate the applicability of dGAMLSS for building normative charts in clinical, genomics, and neuroimaging settings for outcomes drawn from various GAMLSS family distributions [@johnsonMIMICIVFreelyAccessible2023; @mullerGutMicrobiomemetabolomeDataset2022; @bethlehemBrainChartsHuman2022].
