# Methods

We develop a distributed GAMLSS algorithm (dGAMLSS) based on the Rigby and Stasinopoulos (RS) algorithm for GAMLSS fitting [@rigbySemiparametricAdditiveModel1996; @rigbyGeneralizedAdditiveModels2005]. Ultimately, the dGAMLSS algorithm provides distributed machinery for exact fitting of GAMLSS for distributions with up to four parameters across multiple sites without sharing any patient-level data. For each parameter, dGAMLSS can fit fixed effect covariates as well as up to one smooth term defined using either a fixed effect smooth term, a penalized smooth term with a fixed penalty hyperparameter, or a penalized smooth term with an automatically-selected penalty hyperparameter [@eilersFlexibleSmoothingBsplines1996]. Once the dGAMLSS model fitting has converged, dGAMLSS provides distributed inference and estimates model-based quantiles.

## Distributed RS algorithm

We provide necessary notation in Table 1. The pooled RS algorithm is described in Appendix B and Appendix C of @rigbyGeneralizedAdditiveModels2005. Briefly, the RS algorithm consists of two cycles which result in maximization of the pooled likelihood with respect to the fixed effect and smoothing coefficients. The outer cycle iterates across the $p$ GAMLSS distribution-specific parameters. Meanwhile, the inner cycle performs Newton-Raphson updates on the outer-cycle parameter-wise coefficients while keeping coefficients for all other parameters constant. In a pooled setting where all data is available, each Newton-Raphson update can be analytically solved using weighted least squares on the adjusted dependent vector $\boldsymbol{z}_{\_k}$ with diagonal weight matrix $\boldsymbol{W}_{\_k}$, where the underscore represents that the matrices are pooled across all $m$ sites. Since $\boldsymbol{z}_{\_k}$ and the diagonal of $\boldsymbol{W}_{\_k}$ are easily horizontally partitioned into site-specific $\boldsymbol{z}_{ik}$ and $\boldsymbol{W}_{ik}$, updates can easily be distributed across sites -- as long as each site $i$ sends matrices $M_{i1}$ and $M_{i2}$ to a central site, the exact pooled weighted least squares solution can be obtained with one round of communication per inner cycle iteration. Thus, dGAMLSS is an exact solution for federated learning in the GAMLSS setting.

Each inner cycle is completed when all parameter-wise coefficients have converged when compared to the prior Newton-Raphson update. The outer cycle is completed when all coefficients across all parameters have converged when compared to their values at the end of the prior outer cycle. Though standard pooled GAMLSS defines convergence using change in global deviance, dGAMLSS defines convergence using coefficient-wise convergence since global deviance estimation is delayed by one communication round. A given coefficient is considered to be converged when the proportion change between its current value and its previous value is smaller than some user-specific value, $c$. Larger values of $c$ allow for faster, but potentially less stable, convergence of the RS algorithm while smaller values of $c$ result in stable convergence at the cost of more iterations. In the pooled GAMLSS setting, specification of $c$ is easy -- it can be made arbitrarily small since additional iterations are computationally cheap. In dGAMLSS, we find $c = 0.05$ to be well-balanced with respect to stability and communication cost. The exact distributed RS algorithm is provided in Algorithm 1.

## Distributed semi-parametric regression

The pooled RS algorithm describes an additional backfitting cycle within the inner cycles. This backfitting lets GAMLSS find unique solutions when multiple smooth terms are present for each parameter, similarly to a generalized additive model (GAM) [@hastieGeneralizedAdditiveModels1986]. However, in the distributed setting, true backfitting requires many more additional communication rounds within each inner cycle and for each smooth term within each inner cycle, resulting in a multiplicative effect on the total communication rounds that would be prohibitive. Instead, we provide three distributed RS approaches of increasing complexity for fitting up to one smooth term per parameter. We first discuss using fixed effect smooth terms, where wiggliness of the smooth term is directly controlled by limiting the number of spline knots. Next, we describe fixed penalty smooth terms, where the spline basis is over-specified with more knots than necessary and wiggliness of the smooth term is controlled via a known penalty hyperparameter. Finally, we propose an algorithm for fully-automated penalty selection for smooth terms using either generalized cross validation (GCV) or generalized Akaike information criterion (GAIC). For all smooth terms in dGAMLSS, we use B-splines, but other types of splines can also be used. 

### Distributed knot placement and smooth design matrix specification

To fit a given smooth term, dGAMLSS requires that a common spline basis be used across all $i$ sites. This basis must be chosen such that the global minimum and global maximum for the relevant covariate are contained within the boundary knots of the spline, an identical number of knots are used across sites, and knots are placed at identical locations across sites. Knots can either be placed at regular intervals over the range of the covariate values or at approximate quantiles of the relevant covariate for maximum efficiency. If fixed effect smooth terms are used, either knot placement approach can be used -- regular interval knots are easier to place, while approximate quantile are more efficient but require additional information to be sent in the first communication round. For fixed effect smooth terms, a total of $EDF - 1$ knots should be placed, including the two boundary knots, in order to achieve a given desired EDF. This is somewhat different from the standard placement of $EDF - 2$ knots to achieve the desired EDF and is a result of how dGAMLSS avoids backfitting, discussed in-depth below. If fixed penalty smooth terms are used, regular interval knot placement is adequate, given that enough knots are placed, and EDF is controlled using a penalty hyperparameter, discussed below.

One round of pre-fitting communication is required to specify the spline basis. If regular interval knots are desired, each site must send site-specific ranges for the relevant covariate such that the global range can be calculated. Knots can then be placed at regular intervals along this global range by the central site, and these knot locations can be sent back to other sites.

If approximate quantile knots are desired, relevant summary statistics should also be simultaneously sent in this communication round, such as site sample size as well as site-specific covariate means and standard deviations (if the covariate distribution is thought to be nearly normal) or some number of quantiles (if the covariate distribution is thought to be non-normal). If site-specific covariate means and standard deviations are sent, these summary statistics and the site sample sizes can be used by the central site to estimate the pooled covariate mean and standard deviation and therefore obtain approximate quantiles. If site-specific quantiles, such as deciles are sent, the central site can simulate an appropriate number of uniformly distributed observations for each site within each decile, pool simulated observations across sites, and obtain approximate quantiles. These approximate quantiles can be sent back to other sites as the final knot locations.

For fixed effect smooth terms and fixed penalty smooth terms, once knots are placed, a common spline basis across all sites is achieved. Notably, the spline basis is linearly dependent with the intercept such that simultaneous estimation of an intercept and smooth term has infinite solutions. In standard spline-based models, this issue is overcome via backfitting, which constrains smooth terms to have a mean of 0 and therefore maintains independent interpretation of the intercept and the smooth term. In the absence of backfitting, we achieve a similar interpretation via orthogonalization. We first generate a simulated smooth design matrix across the range of the smooth covariate using the spline basis, defined above. Then, we replace the first column of this simulated smooth design matrix with a column of 1s such that the overall span of the simulated smooth design matrix is identical. This new smooth design matrix is then orthogonalized using QR decomposition with respect to the column of 1s. The resulting $\boldsymbol{R}$ matrix can then be sent to other sites along with the common spline basis knots. Each site can then generate its site-specific smooth design matrices using the common spline basis, replace the first column of these matrices with an intercept column, orthogonalize the resulting matrices using the $\boldsymbol{R}^{-1}$ matrix, drop the intercept column so that an intercept can be specified at the model level, and obtain their final, intercept-orthogonal smooth design matrix, $\boldsymbol{Z}_{ik}$. Optionally, orthogonalization can be skipped, and an intercept-free model can be fit. Note that, regardless of what model is fit, orthogonalized coefficients can be transformed to non-orthogonalized coefficients via left multiplication by the $\boldsymbol{R}^{-1}$ matrix.

For fixed penalty or automated penalty smooth terms, additional information is necessary to learn the relationship between $\lambda_k$ and smooth term EDF, where each site must provide one additional round of pre-fitting communication containing site-specific matrices $[\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}]^T [\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}]$ for each parameter containing penalized smooths. To do so, a common spline basis is defined as above, and a joint penalty matrix across the fixed effects and smooth term is automatically specified based on the spline basis [@eilersFlexibleSmoothingBsplines1996]. This joint penalty matrix for parameter $k$, $\boldsymbol{P}_{k}$, is a four-block square matrix of size $\text{length}(\beta_k) + \text{length}(\gamma_k)$, where the bottom right block matrix is the $\text{length}(\gamma_k) \times \text{length}(\gamma_k)$ spline penalty matrix and the other three block matrices are $\boldsymbol{0}$ matrices of appropriate size. This joint specification of the penalty matrix allows for direct fitting of the fixed effects and smooth terms without backfitting. Note that, if orthogonalization is performed for the smooth design matrix, the standard B-spline penalty matrix must be appropriately transformed using the $\boldsymbol{R}^{-1}$ matrix from above. Finally, the following formula is used to obtain the final EDF of the smooth term for any given penalty hyperparameter $\lambda_k$:

$$EDF = tr((\sum_i^m [\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}]^T [\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}] + \lambda_k \boldsymbol{P}_{k})^{-1} (\sum_i^m [\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}]^T [\boldsymbol{X}_{ik} \: \boldsymbol{Z}_{ik}]^T))$$.

Once necessary smooth design matrices and penalty matrices, as necessary, are defined, model fitting can proceed as described in Algorithm 1.

## Distributed inference

Once the distributed RS algorithm has converged and coefficient point estimates are obtained, estimated GAMLSS quantiles can be easily obtained for the reference population as well as any given new data. For reference population quantiles, the central site can simulate data on a grid across all covariates. These simulated covariates can be combined with coefficient point estimates to obtain predicted distributions for each set of covariates, and reference quantiles can be obtained from these predicted distributions. Covariates from new data can be directly used to estimate predicted distributions, and quantiles for outcomes from new data can be estimated.

To perform inference, one additional round of post-fitting communication is necessary. The coefficient point estimates are sent to each site, and each site returns numerical site-wise likelihood-based Hessians, $\boldsymbol{H}_i$, simultaneously evaluated across all parameters. The global covariance matrix, $\boldsymbol{\Sigma} = \boldsymbol{H}^{-1} = (\sum_i^m \boldsymbol{H}_i)^{-1}$, is calculated by inverting the sum of site-specific Hessians. The diagonal of this covariance matrix is used in GAMLSS to obtain standard errors and t-statistics for each coefficient and therefore perform Wald-type inference. In this round of communication, site-specific deviances for the final model are also returned and summed to obtain the global deviance of the model.

For models using fixed effect smooth terms and fixed penalty smooth terms, inference on the overall effect of the spline can be performed via likelihood ratio test comparing the global deviance of a full model with smooth terms to the global deviance of a reduced intercept-only model, where the null distribution of the likelihood ratio test is $\chi^2_\text{df}$, where df is the number of columns of the fixed effect smooth term or the EDF of the fixed penalty smooth term being tested. Note that if multiple parameters contain smooth terms, inference for a given parameter requires a reduced intercept-only model for that parameter only; other parameters must still contain their full smooth terms. To reduce overall communication rounds, if likelihood ratio test inference is desired, reduced models should be fit simultaneously to full models.

For models using automated penalty smooth terms, use of the likelihood ratio test discussed above may be overly liberal since it does not appropriately account for the data-driven choice of $\lambda_k$. Exact inference is not implemented for smooth terms in this context. However, in many GAMLSS settings where the goal is to predict the quantiles of new data given their covariates, optimally-penalized smooth terms may be desirable for their accurate model fit, despite the lack of inference.

## dGAMLSS applications

We apply dGAMLSS to estimate body mass index (BMI) charts using electronic health record (EHR) data, microbiome relative abundance charts using curated gut microbiome-metabolome data, and brain charts using data from the Lifespan Brain Chart Consortium [@johnsonMIMICIVFreelyAccessible2023; @mullerGutMicrobiomemetabolomeDataset2022; @bethlehemBrainChartsHuman2022]. To demonstrate the various smooth term implementations in dGAMLSS, we use fixed effect smooth terms with regular interval knots in the BMI setting, fixed penalty smooth terms in the microbiome setting, and automated penalty smooth terms in the brain chart setting.

For the sake of direct comparison to the gold-standard model in the fixed effect and fixed penalty models, we first fit the gold-standard GAMLSS model on pooled data in order to choose the GAMLSS family distribution and EDF for each parameter. In real-life applications where gold-standard GAMLSS family distribution and EDF are not available, we recommend fitting a local site-specific GAMLSS model in the site that is likely to be relatively representative of the overall population. Optimal EDF for that site can be used for dGAMLSS fitting across sites, potentially with small increases in the estimated EDF to allow for additional wiggliness when fitting on the whole population. For the automated penalty model, we use the gold-standard GAMLSS model to choose the GAMLSS family distribution only.

To compare dGAMLSS results to pooled GAMLSS results, we compare dGAMLSS predicted quantiles to pooled GAMLSS predicted quantiles for each observation, where the pooled GAMLSS function is run using penalized B-splines with default, maximum-likelihood penalty selection criteria. Additionally, in the two applications where dGAMLSS is fit using fixed effect smooth terms, we compare dGAMLSS coefficient and standard error estimates to those from pooled GAMLSS models where fixed effect smooth terms are used instead of penalized B-splines. In the application where dGAMLSS is fit using fixed penalty smooth terms or automated penalty smooth terms, we forego this additional coefficient-wise comparison, since smooth effect coefficients cannot be directly compared across models with different basis specification. Finally, to characterize the average number of communication rounds necessary to fit a dGAMLSS model, we bootstrap each dataset 100 times, fit dGAMLSS models for each bootstrapped dataset, and record the total number of communication rounds.

### BMI modeling

### Microbiome relative abundance modeling

### Brain volumetric modeling
